"""
Defines the constants regarding to the debugging logger.
"""


LOGGER_NAME = 'PokerPy'
LOGGER_FORMAT = '%(name)s (%(levelname)s): %(message)s'

INTERNAL_WRAPPER_LENGTH = 70
INTERNAL_WRAPPER_LEFT_JUST = 10
INTERNAL_WRAPPER_CHAR = '·'

MIDDLE_WRAPPER_LENGTH = 70
MIDDLE_WRAPPER_LEFT_JUST = 10
MIDDLE_WRAPPER_CHAR = '-'

EXTERNAL_WRAPPER_LENGTH = 70
EXTERNAL_WRAPPER_LEFT_JUST = 10
EXTERNAL_WRAPPER_CHAR = '='